title: 'Grace Jacobson'
description: "Grace Jacobson"
baseurl: ""
url: "https://gracejacobson.github.io/"

header_pages:
  - index.md
  - about_me
  - projects.md
  - resume.md

style: light

footer: 'contact: gejacobs@ucsc.edu'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
style: light
