title: 'Grace Jacobson'
description: "Grace Jacobson"
baseurl: ""
url: "https://gracejacobson.github.io/"

header_pages:
  - index.md
  - projects.md
  - resume.md

style: dark

footer: 'check out my <a href="https://github.com/gracejacobson">github</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
